SELECT CPS.NAME_OF_SCHOOL, CD.COMMUNITY_AREA_NAME, CPS.AVERAGE_STUDENT_ATTENDANCE
    FROM CHICAGO_PUBLIC_SCHOOLS AS CPS
    LEFT JOIN CENSUS_DATA AS CD ON CD.COMMUNITY_AREA_NUMBER = CPS.COMMUNITY_AREA_NUMBER
    WHERE CD.HARDSHIP_INDEX = '98';


SELECT CC.CASE_NUMBER, CC.PRIMARY_TYPE, CD.COMMUNITY_AREA_NAME
    FROM CHICAGO_CRIME_DATA AS CC
    LEFT JOIN CENSUS_DATA AS CD ON CC.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER
    WHERE CC.LOCATION_DESCRIPTION LIKE 'SCHOOL%';





